definitions:
  api_account_ginhandler.HelloRequest:
    properties:
      name:
        description: 名字
        example: John
        type: string
    type: object
  api_account_ginhandler.HelloResponse:
    properties:
      message:
        description: 响应消息
        example: Hello, John
        type: string
    type: object
  api_account_ginhandler.LoginRequest:
    properties:
      password:
        description: 密码
        example: securepassword
        type: string
      username:
        description: 用户名
        example: john_doe
        type: string
    type: object
  api_account_ginhandler.LoginResponse:
    properties:
      code:
        description: 响应码
        example: 200
        type: integer
      message:
        description: 响应消息
        example: Login successful
        type: string
      token:
        description: 认证令牌
        example: some-token
        type: string
    type: object
  api_account_ginhandler.RegisterRequest:
    properties:
      email:
        description: 邮箱
        example: john@example.com
        type: string
      password:
        description: 密码
        example: securepassword
        type: string
      username:
        description: 用户名
        example: john_doe
        type: string
    type: object
  api_account_ginhandler.RegisterResponse:
    properties:
      code:
        description: 响应码
        example: 201
        type: integer
      message:
        description: 响应消息
        example: Registration successful
        type: string
    type: object
  ginhandler.PutKeyRequest:
    properties:
      bucket:
        description: 桶名称
        example: my-bucket
        type: string
      data:
        description: 文件内容
        items:
          type: integer
        type: array
      key:
        description: 文件路径
        example: images/logo.png
        type: string
    type: object
  ginhandler.PutKeyResponse:
    properties:
      code:
        description: 响应码
        example: 200
        type: integer
      message:
        description: 响应消息
        example: PutKey successful
        type: string
    type: object
info:
  contact: {}
paths:
  /account/hello:
    get:
      consumes:
      - application/json
      description: 向账号服务发送问候请求
      parameters:
      - description: 问候参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api_account_ginhandler.HelloRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_account_ginhandler.HelloResponse'
      summary: 账号服务问候接口
      tags:
      - Account
  /account/login:
    post:
      consumes:
      - application/json
      description: 用户登录账号
      parameters:
      - description: 登录参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api_account_ginhandler.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_account_ginhandler.LoginResponse'
      summary: 账号登录接口
      tags:
      - Account
  /account/register:
    post:
      consumes:
      - application/json
      description: 用户注册账号
      parameters:
      - description: 注册参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api_account_ginhandler.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_account_ginhandler.RegisterResponse'
      summary: 账号注册接口
      tags:
      - Account
  /s3/PutKey:
    post:
      consumes:
      - application/json
      description: 上传文件内容
      parameters:
      - description: 上传参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/ginhandler.PutKeyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ginhandler.PutKeyResponse'
      summary: 上传文件到 S3
      tags:
      - S3
swagger: "2.0"
